In [13]:

# check xgboost version
import xgboost
print(xgboost.__version__)


2.0.3


In [14]:
import numpy as np
import copy as cp
import matplotlib.pyplot as plt

import seaborn as sns
from typing import Tuple
from sklearn.metrics import confusion_matrix

def cross_val_predict(model, kfold, X, y ) -> Tuple[np.array, np.array, np.array]:

    model_ = cp.deepcopy(model)
    
    no_classes = len(np.unique(y))
    
    actual_classes = np.empty([0], dtype=int)
    actual_X_val = np.empty([0], dtype=int)
    predicted_classes = np.empty([0], dtype=int)
    predicted_proba = np.empty([0, no_classes]) 

    for train_ndx, test_ndx in kfold.split(X):

        train_X, train_y, test_X, test_y = X[train_ndx], y[train_ndx], X[test_ndx], y[test_ndx]

        actual_classes = np.append(actual_classes, test_y)
        actual_X_val = np.append(actual_X_val,test_X)

        model_.fit(train_X, train_y)
        predicted_classes = np.append(predicted_classes, model_.predict(test_X))

        try:
            predicted_proba = np.append(predicted_proba, model_.predict_proba(test_X), axis=0)
        except:
            predicted_proba = np.append(predicted_proba, np.zeros((len(test_X), no_classes), dtype=float), axis=0)

    return actual_classes, predicted_classes, predicted_proba, actual_X_val

In [15]:
def plot_confusion_matrix(actual_classes, predicted_classes, sorted_labels):

    matrix = confusion_matrix(actual_classes, predicted_classes, labels=sorted_labels)
    
    plt.figure(figsize=(12.8,6))
    sns.heatmap(matrix, annot=True, xticklabels=sorted_labels, yticklabels=sorted_labels, cmap="Blues", fmt="g")
    plt.xlabel('Predicted'); plt.ylabel('Actual'); plt.title('Confusion Matrix')

    plt.show()

In [34]:
# try cross validation
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
import sklearn

from sklearn.model_selection import KFold
# linear regression feature importance
# from sklearn.datasets import make_regression
from matplotlib import pyplot
from pandas import read_csv
from sklearn.model_selection import train_test_split

# xgboost for feature importance on a classification problem
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
from matplotlib import pyplot
# define dataset

data_name_vec = ['Fitting', 'Ade', 'Sampling']
for data_name in data_name_vec :
    # data_name = 'Ade'
    XFileName = 'X_codon_stim_' + data_name + '.csv'
    yFileName = 'y_codon_stim_' + data_name + '.csv'
    SaveFileName = 'XGBClassification_' + data_name + '.csv'
            # SaveFileName = 'XGBRegression_only_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'
            # SaveFileName = 'XGBRegression_with_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'

    X = read_csv(XFileName,header = None)
    #print(X.shape)            
    y = read_csv(yFileName,header = None)
    #print(y.shape)
    kfold = KFold(n_splits = 5, shuffle = True, random_state = 1)

    actual_classes, predicted_classes, _ , actual_X_val= cross_val_predict(model, kfold, X.to_numpy(), y.to_numpy())
    # plot_confusion_matrix(actual_classes, predicted_classes, ["TNF", "Pam3CSK", "CpG", "LPS", "PolyIC"])
    #print(actual_classes,predicted_classes)
    confu_mat = confusion_matrix(actual_classes,predicted_classes)
    print(data_name)
    print(confu_mat)
    #accuracy = model.score(actual_X_val, predicted_classes)
    #print(accuracy)

/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector 

Fitting
[[605  12   4   1  10]
 [ 23 387  40  96  41]
 [  6  65 158  63  74]
 [  3 147  41 185  36]
 [  2  44  47  20 435]]


/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector 

Ade
[[531  30   9   8  54]
 [ 39 329  40 108  71]
 [ 27 102 106  65  66]
 [ 15 175  45 147  30]
 [ 37 101  31  18 361]]


/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/Users/admin/anaconda3/envs/envpy311/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector 

Sampling
[[579   7   2   7   5]
 [ 27 378  83  88  24]
 [  6  87 328  94  85]
 [ 19  77  94 380  30]
 [  3  29  82  18 468]]


In [31]:
# random forest for feature importance on a classification problem
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
import sklearn
# linear regression feature importance
# from sklearn.datasets import make_regression
from matplotlib import pyplot
from pandas import read_csv
from sklearn.model_selection import train_test_split

# xgboost for feature importance on a classification problem
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
from matplotlib import pyplot
# define dataset

# 'Fitting' 'Ade' 'Sampling'
data_name = 'Ade'
XFileName = 'X_codon_stim_' + data_name + '.csv'
yFileName = 'y_codon_stim_' + data_name + '.csv'
SaveFileName = 'XGBClassification_' + data_name + '.csv'
            # SaveFileName = 'XGBRegression_only_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'
            # SaveFileName = 'XGBRegression_with_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'

X = read_csv(XFileName,header = None)
print(X.shape)            
y = read_csv(yFileName,header = None)
print(y.shape)

# X, y = make_classification(n_samples=1000, n_features=3, n_informative=2, n_redundant=1, random_state=1, n_classes = 2)
# print(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

#print(y_train)
#print(y)
# define the model
# define dataset
model = RandomForestClassifier()

# fit the model
y_train = y_train.iloc[:, 0]
print(y_train)

model.fit(X_train, y_train)
# evaluate the model
y_pred = model.predict(X_test)
print(y_pred.shape)
# get importance
importance = model.feature_importances_

# import fitting data:

data_name_2 = 'Fitting'
XFileName_2 = 'X_codon_stim_' + data_name + '.csv'
yFileName_2 = 'y_codon_stim_' + data_name + '.csv'
SaveFileName_2 = 'XGBClassification_' + data_name + '.csv'
            # SaveFileName = 'XGBRegression_only_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'
            # SaveFileName = 'XGBRegression_with_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'

X_2 = read_csv(XFileName,header = None)
print(X_2.shape)            
y_2 = read_csv(yFileName,header = None)
print(y_2.shape)

# X, y = make_classification(n_samples=1000, n_features=3, n_informative=2, n_redundant=1, random_state=1, n_classes = 2)
# print(X)
X_train, X_test, y_train, y_test = train_test_split(X_2, y_2, test_size=0.33, random_state=1)

y_pred = model.predict(X_test)

confu_mat = confusion_matrix(y_test,y_pred)
# np.savetxt(SaveFileName,confu_mat,  delimiter=",")  #fmt = '%d',
accuracy = model.score(X_test, y_test)
print(accuracy)
print(confu_mat)

#y_pred_2 = model.predict(X_2)

#confu_mat = confusion_matrix(y_2,y_pred_2)
# np.savetxt(SaveFileName,confu_mat,  delimiter=",")  #fmt = '%d',
#accuracy = model.score(X_2, y_2)
#print(accuracy)
#print(confu_mat)

(2545, 6)
(2545, 1)
2532    4
1637    3
2393    4
1628    3
2095    4
       ..
960     1
905     1
1096    1
235     0
1061    1
Name: 0, Length: 1705, dtype: int64
(840,)
(2545, 6)
(2545, 1)
0.5845238095238096
[[172   6   2   4  17]
 [ 13 103  16  46  15]
 [  7  26  51  29  27]
 [  2  55  13  53  12]
 [ 15  30   5   9 112]]


In [30]:
# random forest for feature importance on a classification problem
from sklearn.ensemble import RandomForestClassifier

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import csv
import sklearn
# linear regression feature importance
# from sklearn.datasets import make_regression
from matplotlib import pyplot
from pandas import read_csv
from sklearn.model_selection import train_test_split

# xgboost for feature importance on a classification problem
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix
from xgboost import XGBClassifier
from matplotlib import pyplot
# define dataset

# 'Fitting' 'Ade' 'Sampling'
data_name = 'Fitting'
XFileName = 'X_codon_stim_' + data_name + '.csv'
yFileName = 'y_codon_stim_' + data_name + '.csv'
SaveFileName = 'XGBClassification_' + data_name + '.csv'
            # SaveFileName = 'XGBRegression_only_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'
            # SaveFileName = 'XGBRegression_with_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'

X = read_csv(XFileName,header = None)
print(X.shape)            
y = read_csv(yFileName,header = None)
print(y.shape)

# X, y = make_classification(n_samples=1000, n_features=3, n_informative=2, n_redundant=1, random_state=1, n_classes = 2)
# print(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)

#print(y_train)
#print(y)
# define the model
# define dataset
model = RandomForestClassifier()

# fit the model
y_train = y_train.iloc[:, 0]
print(y_train)

model.fit(X_train, y_train)


# import fitting data:

data_name_2 = 'Ade'
XFileName_2 = 'X_codon_stim_' + data_name + '.csv'
yFileName_2 = 'y_codon_stim_' + data_name + '.csv'
SaveFileName_2 = 'XGBClassification_' + data_name + '.csv'
            # SaveFileName = 'XGBRegression_only_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'
            # SaveFileName = 'XGBRegression_with_randompara_' + FeatureLig + '_' + Ligand + '_' + DoseSymbol + '.csv'

X_2 = read_csv(XFileName,header = None)
print(X_2.shape)            
y_2 = read_csv(yFileName,header = None)
print(y_2.shape)

# X, y = make_classification(n_samples=1000, n_features=3, n_informative=2, n_redundant=1, random_state=1, n_classes = 2)
# print(X)
X_train, X_test, y_train, y_test = train_test_split(X_2, y_2, test_size=0.33, random_state=1)

y_pred = model.predict(X_test)

confu_mat = confusion_matrix(y_test,y_pred)
# np.savetxt(SaveFileName,confu_mat,  delimiter=",")  #fmt = '%d',
accuracy = model.score(X_test, y_test)
print(accuracy)
print(confu_mat)

(2545, 6)
(2545, 1)
2532    4
1637    3
2393    4
1628    3
2095    4
       ..
960     1
905     1
1096    1
235     0
1061    1
Name: 0, Length: 1705, dtype: int64
(2545, 6)
(2545, 1)
0.7083333333333334
[[195   5   1   0   0]
 [  8 127  12  33  13]
 [  2  22  71  23  22]
 [  1  48  13  63  10]
 [  1  13  14   4 139]]
